// Auto-generated by scripts/generate-manifest.py. Do not hand-edit media arrays.
var PORTFOLIO_PROJECTS = {
  "nevuary": {
    "title": "Nevuary",
    "tag": "Video & Photography",
    "description": "A full campaign for Nevuary's racing jacket drop, from studio product shots to street-style campaign photography and short-form video across two locations. We built a visual world that matched the brand's motorsport-meets-streetwear identity, shot to move fast across Instagram and TikTok.",
    "media": [
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/001.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/002.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/003.webp"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/001.mp4",
        "poster": "images/portfolio/nevuary.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/004.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/005.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/006.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/007.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/008.webp"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/002.mp4"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/009.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/010.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/011.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/012.webp"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/003.mp4"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/013.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/014.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/015.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/016.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/017.webp"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/004.mp4"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/018.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/019.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/020.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/021.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/022.webp"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/005.mp4"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/023.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/024.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/025.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/026.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/027.webp"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/006.mp4"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/028.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/029.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/030.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/031.webp"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/007.mp4"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/032.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/033.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/034.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/035.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/036.webp"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/008.mp4"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/037.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/038.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/039.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/040.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/041.webp"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/009.mp4"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/042.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/043.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/044.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/045.webp"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/010.mp4"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/046.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/047.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/048.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/049.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/050.webp"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/011.mp4"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/051.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/052.webp"
      }
    ]
  },
  "fresh-pop": {
    "title": "Fresh Pop",
    "tag": "Video",
    "description": "Street-style video content for Fresh Pop, built entirely around movement and location. Short, punchy edits designed for the scroll. No posed shots, just real energy.",
    "media": [
      {
        "type": "video",
        "src": "images/portfolio/video/full/fresh-pop/001.mp4",
        "poster": "images/portfolio/fresh-pop.webp"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/fresh-pop/002.mp4"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/fresh-pop/003.mp4"
      }
    ]
  },
  "riverridge": {
    "title": "RiverRidge",
    "tag": "Commercial & Event",
    "description": "Ongoing brand and sponsorship coverage for RiverRidge Waste Management, from equestrian sponsorship at the Balmoral Show to a charity partnership with Northern Ireland Hospice. Coverage built to show up wherever RiverRidge shows up, on-brand every time.",
    "media": [
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/001.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/002.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/003.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/004.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/005.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/006.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/007.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/008.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/009.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/010.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/011.webp"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/riverridge/001.mp4",
        "poster": "images/portfolio/riverridge.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/012.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/013.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/014.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/015.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/016.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/017.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/018.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/019.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/020.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/021.webp"
      }
    ]
  },
  "ulster-rally": {
    "title": "Ulster Rally",
    "tag": "Action",
    "description": "Trackside action photography from the Ulster Rally: fast cars, tight corners and the split-second timing that motorsport photography demands.",
    "media": [
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/001.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/002.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/003.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/004.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/005.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/006.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/007.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/008.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/009.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/010.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/011.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/012.webp"
      }
    ]
  },
  "moo-town": {
    "title": "Moo Town Creamery",
    "tag": "Food",
    "description": "Bright, appetite-driving product photography for Moo Town Creamery, built to make every scoop look exactly as good as it tastes, shot for their menu, socials and seasonal campaigns.",
    "media": [
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/001.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/002.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/003.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/004.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/005.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/006.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/007.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/008.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/009.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/010.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/011.webp"
      }
    ]
  },
  "portrait": {
    "title": "Portrait",
    "tag": "Photography",
    "description": "A collection of portrait work across multiple shoots and subjects. Proof that good portrait photography is about direction and light, not just the person in front of the camera.",
    "media": [
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/001.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/002.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/003.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/004.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/005.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/006.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/007.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/008.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/009.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/010.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/011.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/012.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/013.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/014.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/015.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/016.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/017.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/018.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/019.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/020.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/021.webp"
      }
    ]
  },
  "event": {
    "title": "Event",
    "tag": "Photography",
    "description": "Event photography built to capture the moments people actually remember: the reactions, not just the room.",
    "media": [
      {
        "type": "image",
        "src": "images/portfolio/full/event/001.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/002.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/003.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/004.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/005.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/006.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/007.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/008.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/009.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/010.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/011.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/012.webp"
      }
    ]
  },
  "flawless-finesse": {
    "title": "Flawless Finesse Detailing",
    "tag": "Video",
    "description": "A promo video for Flawless Finesse Detailing, built around the most satisfying part of the job: foam, water and a car going from dull to showroom in sixty seconds.",
    "media": [
      {
        "type": "video",
        "src": "images/portfolio/video/full/flawless-finesse/001.mp4",
        "poster": "images/portfolio/flawless-finesse.webp"
      }
    ]
  },
  "ni-hospice": {
    "title": "NI Hospice",
    "tag": "RiverRidge · Video",
    "description": "A short film documenting RiverRidge's donation partnership with Northern Ireland Hospice. A reminder that sponsorship content can do more than put a logo on a banner.",
    "media": [
      {
        "type": "video",
        "src": "images/portfolio/video/full/ni-hospice/001.mp4",
        "poster": "images/portfolio/ni-hospice.webp"
      }
    ]
  },
  "star-barbers": {
    "title": "Star Barbers",
    "tag": "Video",
    "description": "A promo video for Star Barbers, built around the cut itself: the clippers, the finishing touches and the finished look walking out the door.",
    "media": [
      {
        "type": "video",
        "src": "images/portfolio/video/full/star-barbers/001.mp4",
        "poster": "images/portfolio/star-barbers.webp"
      }
    ]
  }
};
