// Auto-generated by scripts/generate-manifest.py — do not hand-edit media arrays.
var PORTFOLIO_PROJECTS = {
  "nevuary": {
    "title": "Nevuary",
    "tag": "Video & Photography",
    "description": "A full campaign for Nevuary's racing jacket drop — from studio product shots to street-style campaign photography and short-form video across two locations. We built a visual world that matched the brand's motorsport-meets-streetwear identity, shot to move fast across Instagram and TikTok.",
    "media": [
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/001.mp4",
        "poster": "images/portfolio/nevuary.webp"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/002.mp4"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/003.mp4"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/004.mp4"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/005.mp4"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/006.mp4"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/007.mp4"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/008.mp4"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/009.mp4"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/010.mp4"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/nevuary/011.mp4"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/001.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/002.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/003.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/004.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/005.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/006.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/007.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/008.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/009.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/010.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/011.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/012.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/013.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/014.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/015.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/016.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/017.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/018.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/019.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/020.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/021.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/022.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/023.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/024.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/025.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/026.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/027.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/028.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/029.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/030.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/031.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/032.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/033.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/034.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/035.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/036.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/037.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/038.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/039.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/040.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/041.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/042.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/043.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/044.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/045.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/046.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/047.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/048.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/049.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/050.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/051.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/052.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/053.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/054.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/055.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/056.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/057.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/058.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/059.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/060.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/061.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/062.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/063.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/064.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/065.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/066.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/067.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/068.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/069.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/070.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/071.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/072.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/073.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/074.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/075.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/076.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/077.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/078.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/079.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/080.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/081.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/082.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/083.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/084.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/085.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/086.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/087.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/088.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/089.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/090.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/091.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/092.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/093.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/094.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/095.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/096.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/097.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/098.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/099.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/100.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/101.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/102.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/103.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/104.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/105.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/106.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/107.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/108.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/109.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/110.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/111.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/112.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/113.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/114.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/115.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/116.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/117.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/118.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/119.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/120.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/121.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/122.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/123.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/124.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/125.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/126.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/127.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/128.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/129.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/130.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/131.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/132.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/133.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/134.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/135.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/136.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/137.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/138.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/139.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/140.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/141.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/142.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/143.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/144.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/145.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/146.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/147.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/148.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/149.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/150.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/151.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/152.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/153.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/154.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/155.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/156.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/157.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/158.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/159.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/160.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/161.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/162.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/163.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/164.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/165.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/166.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/167.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/168.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/169.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/170.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/171.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/172.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/nevuary/173.webp"
      }
    ]
  },
  "fresh-pop": {
    "title": "Fresh Pop",
    "tag": "Video",
    "description": "Street-style video content for Fresh Pop, built entirely around movement and location. Short, punchy edits designed for the scroll — no posed shots, just real energy.",
    "media": [
      {
        "type": "video",
        "src": "images/portfolio/video/full/fresh-pop/001.mp4",
        "poster": "images/portfolio/fresh-pop.webp"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/fresh-pop/002.mp4"
      },
      {
        "type": "video",
        "src": "images/portfolio/video/full/fresh-pop/003.mp4"
      }
    ]
  },
  "riverridge": {
    "title": "RiverRidge",
    "tag": "Commercial & Event",
    "description": "Ongoing brand and sponsorship coverage for RiverRidge Waste Management — from equestrian sponsorship at the Balmoral Show to a charity partnership with Northern Ireland Hospice. Coverage built to show up wherever RiverRidge shows up, on-brand every time.",
    "media": [
      {
        "type": "video",
        "src": "images/portfolio/video/full/riverridge/001.mp4",
        "poster": "images/portfolio/riverridge.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/001.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/002.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/003.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/004.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/005.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/006.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/007.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/008.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/009.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/010.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/011.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/012.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/013.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/014.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/015.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/016.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/017.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/018.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/019.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/020.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/021.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/022.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/023.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/024.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/025.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/026.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/027.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/028.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/029.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/030.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/031.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/032.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/riverridge/033.webp"
      }
    ]
  },
  "ulster-rally": {
    "title": "Ulster Rally",
    "tag": "Action",
    "description": "Trackside action photography from the Ulster Rally — fast cars, tight corners and the split-second timing that motorsport photography demands.",
    "media": [
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/001.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/002.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/003.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/004.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/005.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/006.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/007.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/008.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/009.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/010.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/011.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/ulster-rally/012.webp"
      }
    ]
  },
  "moo-town": {
    "title": "Moo Town Creamery",
    "tag": "Food",
    "description": "Bright, appetite-driving product photography for Moo Town Creamery — built to make every scoop look exactly as good as it tastes, shot for their menu, socials and seasonal campaigns.",
    "media": [
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/001.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/002.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/003.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/004.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/005.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/006.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/007.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/008.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/009.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/010.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/moo-town/011.webp"
      }
    ]
  },
  "portrait": {
    "title": "Portrait",
    "tag": "Photography",
    "description": "A collection of portrait work across multiple shoots and subjects — proof that good portrait photography is about direction and light, not just the person in front of the camera.",
    "media": [
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/001.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/002.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/003.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/004.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/005.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/006.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/007.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/008.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/009.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/010.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/011.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/012.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/013.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/014.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/015.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/016.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/017.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/018.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/019.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/020.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/portrait/021.webp"
      }
    ]
  },
  "landscape": {
    "title": "Landscape",
    "tag": "Photography",
    "description": "Landscape and nature photography shot around Northern Ireland — from misty mountain sunrises to a wind turbine caught mid-controlled-burn. Proof we can make anything look cinematic.",
    "media": [
      {
        "type": "image",
        "src": "images/portfolio/full/landscape/001.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/landscape/002.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/landscape/003.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/landscape/004.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/landscape/005.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/landscape/006.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/landscape/007.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/landscape/008.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/landscape/009.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/landscape/010.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/landscape/011.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/landscape/012.webp"
      }
    ]
  },
  "event": {
    "title": "Event",
    "tag": "Photography",
    "description": "Event photography built to capture the moments people actually remember — the reactions, not just the room.",
    "media": [
      {
        "type": "image",
        "src": "images/portfolio/full/event/001.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/002.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/003.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/004.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/005.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/006.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/007.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/008.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/009.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/010.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/011.webp"
      },
      {
        "type": "image",
        "src": "images/portfolio/full/event/012.webp"
      }
    ]
  },
  "flawless-finesse": {
    "title": "Flawless Finesse Detailing",
    "tag": "Video",
    "description": "A promo video for Flawless Finesse Detailing, built around the most satisfying part of the job — foam, water and a car going from dull to showroom in sixty seconds.",
    "media": [
      {
        "type": "video",
        "src": "images/portfolio/video/full/flawless-finesse/001.mp4",
        "poster": "images/portfolio/flawless-finesse.webp"
      }
    ]
  },
  "ni-hospice": {
    "title": "NI Hospice",
    "tag": "RiverRidge · Video",
    "description": "A short film documenting RiverRidge's donation partnership with Northern Ireland Hospice — a reminder that sponsorship content can do more than put a logo on a banner.",
    "media": [
      {
        "type": "video",
        "src": "images/portfolio/video/full/ni-hospice/001.mp4",
        "poster": "images/portfolio/ni-hospice.webp"
      }
    ]
  }
};
